config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:show] do
    resources :user_tickets, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draw.rb
class Draw < ApplicationRecord
  belongs_to :ticket
  belongs_to :winner_user_ticket, class_name: 'UserTicket', optional: true
  has_many :draw_participants
end

app/models/draw_participant.rb
class DrawParticipant < ApplicationRecord
  belongs_to :user_ticket
  belongs_to :draw
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  has_many :user_tickets
  has_many :users, through: :user_tickets
  has_many :draws
end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_tickets
  has_many :tickets, -> { distinct }, through: :user_tickets

  has_many :draw_winnings, through: :user_tickets, source: :draw_winner
  has_many :draw_participants, through: :user_tickets

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_ticket.rb
class UserTicket < ApplicationRecord
  belongs_to :user
  belongs_to :ticket

  has_one :draw_winner, foreign_key: 'winner_user_ticket_id', class_name: 'Draw'
  has_many :draw_participants

  def is_draw_winner?(draw)
    return unless draw.is_a? Draw
    draw_winner == draw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/user_tickets_controller.rb
class UserTicketsController < ApplicationController

  def create
    if current_user.user_tickets.create(ticket_id: params[:ticket_id])
      redirect_to user_path(current_user), notice: t('user_ticket.create')
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @draw_participants = current_user.draw_participants.page params[:page]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_ticket_helper.rb
module UserTicketHelper
  def ticket_status(status)
    return I18n.t('common.win') if status
    I18n.t('common.loss')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkSixLottery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_tickets/new.html.erb
<h1>Purchase Ticket</h1>

<div>
  <% Ticket.all.each do |ticket| %>
    <div class="ticket">
      <div><%= ticket.title %></div>
      <div><%= ticket.winning_amount.to_s %></div>
      <div> <%= button_to t('common.buy') , user_user_tickets_path, method: :post, params: {ticket_id: ticket.id} %> </div>
    </div>
  <% end %>
<div style="clear:both;"></div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('common.welcome') %></strong>
  <%= current_user.email %>
</p>

<h1>Draws List</h1>

<table>
  <thead>
    <tr>
      <th><%= I18n.t('table.title') %></th>
      <th><%= I18n.t('table.ticket') %></th>
      <th><%= I18n.t('table.performed_at') %></th>
      <th><%= I18n.t('table.status') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @draw_participants.each do |draw_participant| %>
      <tr>
        <td><%= draw_participant.draw.title %></td>
        <td><%= draw_participant.user_ticket.ticket.title %></td>
        <td><%= draw_participant.draw.created_at %></td>
        <td><%= ticket_status(draw_participant.user_ticket.is_draw_winner?(draw_participant.draw)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @draw_participants %>


<p><%= link_to(I18n.t('common.purchase_ticket'), new_user_user_ticket_path(current_user), method: :get) %></p>
<p><%= link_to(I18n.t('common.logout'), destroy_user_session_path, method: :delete) %></p>